# Generated by Django 4.2.1 on 2023-05-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 18, 43, 23, 719294), verbose_name='Дата'),
        ),
    ]
