# Generated by Django 5.2.17 on 2026-09-14 00:16

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('course', 'Филиал / Департамент'), ('platoon', 'Управление'), ('group', 'Отдел'), ('unit', 'Группа / Команда')], default='course', max_length=25, verbose_name='Тип подразделения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.category', verbose_name='Вышестоящее подразделение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rang',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Junior+', 'Junior+'), ('Middle', 'Middle'), ('Middle+', 'Middle+'), ('Senior', 'Senior'), ('Lead', 'Team Lead'), ('Principal', 'Principal Expert'), ('Manager', 'Manager'), ('Head', 'Head of Department'), ('Director', 'Director'), ('VP', 'Vice President'), ('Executive', 'Executive')], max_length=50, null=True, verbose_name='Корпоративный грейд'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Сотрудник'), (2, 'Тимлид группы'), (3, 'Руководитель направления'), (4, 'Куратор подразделения'), (5, 'Операционный менеджер'), (6, 'Руководитель департамента')], null=True, verbose_name='Роль / Должность'),
        ),
        migrations.AlterField(
            model_name='note',
            name='cadet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Достижение', 'Достижение / Благодарность'), ('Замечание', 'Замечание / Инцидент'), ('Устранение замечания', 'Устранение замечания / Закрыто')], max_length=50, verbose_name='Вид записи'),
        ),
        migrations.AlterField(
            model_name='note',
            name='who_gave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_notes', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначено'),
        ),
    ]
