# Generated by Django 4.2 on 2023-04-15 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Поощрение'), (2, 'Взыскание'), (3, 'Снятие ранее применённого взыскания')], verbose_name='Вид записи')),
                ('who_gave', models.CharField(max_length=150, verbose_name='Кем дано')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('check_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
