# Generated by Django 4.2 on 2023-04-24 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='note',
            name='cadet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_for_cadet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='who_gave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_who_gave', to=settings.AUTH_USER_MODEL),
        ),
    ]
